### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by leshik** [vanrein/6bed4#1]
Hi,

I tried to build `refimpl-01-alpha2` as well as the `master` branch of this repo, but didn't manage how to make it work. My environment is Ubuntu/Linux 16.04.3 LTS behind NAT. Once I execute `6bed4peer -def` (or `6bed4peer -ref` in case of `master` branch) I get the following output:
```
6bed4peer[20413]: Bound to UDP port 64070
6bed4peer[20413]: No LAN bypass: Failed to setup multicast: Invalid argument
6bed4peer[20413]: Looking up v6addr fe80::c225:6ff:feb0:7ea6
6bed4peer[20413]: Message of 3776 bytes from neighbor cache, total is now 3776
6bed4peer[20413]: Message of 352 bytes from neighbor cache, total is now 352
6bed4peer[20413]: Message of 20 bytes from neighbor cache, total is now 20
6bed4peer[20413]: Failed to find LL
6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service, next attempt in 1 seconds
6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service, next attempt in 3 seconds
6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service, next attempt in 7 seconds
6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service, next attempt in 15 seconds
6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service, next attempt in 30 seconds
```
What can I do to troubleshoot the issue?

**Comment by vanrein** [comment]
Hello Alexey,

We are in fact in transition with the protocol [Henri is doing the hard
work on that] and the default server is also part of the changes.  If
you're not in an awful hurry to get it working, shall we come back to
you after we've completed the changes?

The trace below looks like the problems we are currently working on with
the default server (donated by SURFnet.nl for 10 years to come!) which
relates to UDP passage.

Thanks for your interest -- can I ask what you intend to do with 6bed4? 
Maybe we can help more than you expect :)

-Rick

> Alexey Zagarin <mailto:notifications@github.com>
> 20 December 2017 at 18:12
> Hi,
>
> I tried to build `refimpl-01-alpha2` as well as the `master` branch of
> this repo, but didn't manage how to make it work. My environment is
> Ubuntu/Linux 16.04.3 LTS behind NAT. Once I execute `6bed4peer -def`
> (or `6bed4peer -ref` in case of `master` branch) I get the following
> output:
> ```
> 6bed4peer[20413]: Bound to UDP port 64070
> 6bed4peer[20413]: No LAN bypass: Failed to setup multicast: Invalid
> argument
> 6bed4peer[20413]: Looking up v6addr fe80::c225:6ff:feb0:7ea6
> 6bed4peer[20413]: Message of 3776 bytes from neighbor cache, total is
> now 3776
> 6bed4peer[20413]: Message of 352 bytes from neighbor cache, total is
> now 352
> 6bed4peer[20413]: Message of 20 bytes from neighbor cache, total is now 20
> 6bed4peer[20413]: Failed to find LL
> 6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service,
> next attempt in 1 seconds
> 6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service,
> next attempt in 3 seconds
> 6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service,
> next attempt in 7 seconds
> 6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service,
> next attempt in 15 seconds
> 6bed4peer[20413]: Sent Router Advertisement to Public 6bed4 Service,
> next attempt in 30 seconds
> ```
> What can I do to troubleshoot the issue?
>

**Comment by leshik** [comment]
Hi Rick,

Thank you for the quick reply.
I'm not in a hurry, and I'll be happy to be in touch once the transition is done.

As you mentioned problems with the default server, may I ask if setting up a fallback server, and then using it by specifying `--v4server` option will help? If yes, what is the recommended way to set up such a server?

My use case for 6bed4 is like this: I have several servers in different parts of the country, all are behind NAT and with no IPv6 connectivity, that I need to interconnect somehow, mainly to set up PostgreSQL bidirectional logical replication. Using OpenVPN is one of the feasible options but too burdensome to set up. All endpoints are encrypted and authenticated, and firewalls are also in place so there should be no security concerns to establish public IPv6 connectivity.

**Comment by vanrein** [comment]
Hi,

>
> As you mentioned problems with the default server, may I ask if
> setting up a fallback server, and then using it by specifying
> `--v4server` option will help? If yes, what is the recommended way to
> set up such a server?


It should.  You can run 6bed4router on that [the executable name has
changed over time, I may be off].  The usual options for test
deployments are -d -e -f

You need the UDP port open, of course.

Our intention is to make an anycast address from 145.136.0.1 -- but I
don't suppose your offering to be the first alias to that ;-)

>
> My use case for 6bed4 is like this: I have several servers in
> different parts of the country, all are behind NAT and with no IPv6
> connectivity, that I need to interconnect somehow, mainly to set up
> PostgreSQL bidirectional logical replication.


Sounds like a good use, though you might find it easier to do with 6to4
tunneling (and lock down its connectivity for others as you see fit). 
You would end up with 2002:<ip4addr>::/48 prefixes.  You do need to have
NATs that pass proto41 for that to work though.

>
> Using OpenVPN is one of the feasible options but too burdensome to set
> up. All endpoints are encrypted and authenticated, and firewalls are
> also in place so there should be no security concerns to establish
> public IPv6 connectivity.


Yes, that sounds clever enough -- not to build on point-to-point
protection but rather do it end-to-end.

FWIW, one of the things we're changing is to let people have their
personal preference of prefix; the 6bed4 logic then rests in the lower
half and the higher half can be of a number of classes, including a
completely local address range in the unique local prefix fc00::/7 --
which I advise you to use for your closed / in-door network.

We will contact you when 6bed4 is finally ready to ship, which is
probably within 1-2 months.  Please note that we will also provide an
Android app that offers the tunnel and its IPv6 addressing to any
application (as a VPNService application).

-Rick

**Comment by leshik** [comment]
Hi,

I tried again, and this time I was able to make it work with dedicated `6bed4router`. However, I had to change `SERVER_6BED4_` defines in `nonstd.h` (apparently, the public IP is hardcoded now and `-s` switch doesn't work). Also, there is some inconsistency in the documentation/sources regarding this public address, somewhere it's `145.136.0.1`, in other places it's `145.100.190.242`.

Besides that, these warnings look confusing:
```
Failed to permit fragmentation -- not all peers may be accessible with MTU 1280
No LAN bypass: Failed to setup multicast: Invalid argument
Looking up v6addr fe80::c225:6ff:feb0:7ea6
Failed to find LL
```
Not sure what `fe80::c225:6ff:feb0:7ea6` is and why `6bed4peer` is looking for it, could you explain, please? Other failures are all seemed related to `setsockopt`, but I have no clue why – I'm using pretty standard Ubuntu 16.04 and all interfaces have MTU size of 1500.

Probably I'm doing something wrong, any help is appreciated.

**Comment by vanrein** [comment]
Hi Alexey,

I'm glad to hear it is now working for you.  We have indeed done some
maintenance, including on the access controls to the server on 145.136.0.1.

The reason that we have a nonstd.h is that we are not permitted to claim
a port until it has passed through IANA.  We tend to copy the "test"
version over nonstd.h to "build in" the 145.136.0.1 server.  The other
address is deprecated / unsupported.  The nonstd.h does indeed need some
work; it has also been edited to represent ports and addresses
differently.  Maybe we should generate these derived forms in the
program itself.


I'm happy that it works for you now!


Cheers,
 -Rick


Alexey Zagarin wrote:
>
> Hi,
>
> I tried again, and this time I was able to make it work with dedicated
> `6bed4router`. However, I had to change `SERVER_6BED4_` defines in
> `nonstd.h` (apparently, the public IP is hardcoded now and `-s` switch
> doesn't work). Also, there is some inconsistency in the
> documentation/sources regarding this public address, somewhere it's
> `145.136.0.1`, in other places it's `145.100.190.242`.
>
> Besides that, these warnings look confusing:
> ```
> Failed to permit fragmentation -- not all peers may be accessible with
> MTU 1280
> No LAN bypass: Failed to setup multicast: Invalid argument
> Looking up v6addr fe80::c225:6ff:feb0:7ea6
> Failed to find LL
> ```
> Not sure what `fe80::c225:6ff:feb0:7ea6` is and why `6bed4peer` is
> looking for it, could you explain, please? Other failures are all
> seemed related to `setsockopt`, but I have no clue why – I'm using
> pretty standard Ubuntu 16.04 and all interfaces have MTU size of 1500.
>
> Probably I'm doing something wrong, any help is appreciated.


> Alexey Zagarin <mailto:notifications@github.com>
> 17 January 2018 at 10:42
> Hi,
>
> I tried again, and this time I was able to make it work with dedicated
> `6bed4router`. However, I had to change `SERVER_6BED4_` defines in
> `nonstd.h` (apparently, the public IP is hardcoded now and `-s` switch
> doesn't work). Also, there is some inconsistency in the
> documentation/sources regarding this public address, somewhere it's
> `145.136.0.1`, in other places it's `145.100.190.242`.
>
> Besides that, these warnings look confusing:
> ```
> Failed to permit fragmentation -- not all peers may be accessible with
> MTU 1280
> No LAN bypass: Failed to setup multicast: Invalid argument
> Looking up v6addr fe80::c225:6ff:feb0:7ea6
> Failed to find LL
> ```
> Not sure what `fe80::c225:6ff:feb0:7ea6` is and why `6bed4peer` is
> looking for it, could you explain, please? Other failures are all
> seemed related to `setsockopt`, but I have no clue why – I'm using
> pretty standard Ubuntu 16.04 and all interfaces have MTU size of 1500.
>
> Probably I'm doing something wrong, any help is appreciated.
>

**Comment by leshik** [comment]
My concern is that it works in relay mode now. I thought that these errors might be related to p2p connectivity somehow...

**Comment by vanrein** [comment]
This issue is resolved, but kept open for the consistency remarks and documentation hints.  Before launching a 1.0 of 6bed4, this will all be cross-checked.  We are working towards a publication of an I-D.
